from gidc.enums import WeaponType
from gidc.core.weapon import Weapon, WeaponSubStat

from ._default import DefaultWeapon
from .claymore import AThousandBlazingSuns, Verdict, ATeaspoonOfTranscendence, GestOfTheMightyWolf, FangOfTheMountainKing, BeaconOfTheReedSea, RedhornStonethresher, SongOfBrokenPines, TheUnforged, WolfsGravestone, SkywardPride
from .sword import (
    PeakPatrolSong, SkywardBlade, AquilaFavonia, Azurelight,
    FavoniusSword, CalamityOfEshu,
    LightbearingMoonshard,
    AthameArtis,
    Absolution,
    UrakuMisugiri,
    SplendorOfTranquilWaters,
    LightOfFoliarIncision,
    KeyOfKhajNisut,
    HaranGeppakuFutsu,
    MistsplitterReforged,
    FreedomSworn,
    PrimordialJadeCutter,
    SummitShaper,
)
from .polearm import (
    ProspectorsShovel, Deathmatch, DialoguesOfTheDesertSages,
    FracturedHalo, SymphonistOfScents, SkywardSpine,
    BloodsoakedRuins,
    DragonsBane,
    FavoniusLance,
    LumidouceElegy,
    CrimsonMoonsSemblance,
    StaffOfTheScarletSands,
    CalamityQueller,
    EngulfingLightning,
    StaffOfHoma,
    VortexVanquisher,
    PrimordialJadeWingedSpear,
)
from .catalyst import (
    StarcallersWatch, CranesEchoingCall, FavoniusCodex, SacrificialFragments,
    ThrillingTalesOfDragonSlayers,
    AngelosHeptades,
    NocturnesCurtainCall,
    VividNotions,
    NewYearsMorningHibernation,
    SurfSUp,
    CashflowSupervision,
    TomeOfTheEternalFlow,
    JadefallSSplendor,
    TulaytullahSRemembrance,
    AThousandFloatingDreams,
    KaguraSVerity,
    EverlastingMoonglow,
    MemoryOfDust,
    LostPrayerToTheSacredWinds,
    SkywardAtlas,
    NightweaverSLookingGlass,
    ReliquaryOfTruth,
)

from .bow import (
    SkywardHarp,
    AmosBow,
)

WEAPON_REGISTRY: dict[str, type[Weapon]] = {
    "타오르는 천 개의 태양": AThousandBlazingSuns,
    "판정":               Verdict,
    "바위산을 맴도는 노래": PeakPatrolSong,
    "천공의 검":           SkywardBlade,
    "매의 검":             AquilaFavonia,
    "창백한 섬광":          Azurelight,
    "페보니우스 검":        FavoniusSword,
    "에슈의 재앙":          CalamityOfEshu,
    "채굴의 삽":           ProspectorsShovel,
    "결투의 창":           Deathmatch,
    "위대한 사막 현자의 대답": DialoguesOfTheDesertSages,
    "파멸의 빛고리":        FracturedHalo,
    "맛의 지휘자":          SymphonistOfScents,
    "천공의 마루":          SkywardSpine,
    "별지기의 시선":        StarcallersWatch,
    "학의 여음":           CranesEchoingCall,
    "페보니우스 비전":      FavoniusCodex,
    "제례의 악장":          SacrificialFragments,
    "드래곤 슬레이어 영웅담": ThrillingTalesOfDragonSlayers,
    "일곱빛 계시":           AngelosHeptades,
    "막간의 야상곡":          NocturnesCurtainCall,
    "빛나는 마음":           VividNotions,
    "피로 물든 성":          BloodsoakedRuins,
    "용학살창":             DragonsBane,
    "페보니우스 장창":         FavoniusLance,
    "등방울꽃의 애가":         LumidouceElegy,
    "붉은 달의 형상":         CrimsonMoonsSemblance,
    "나른한 새해":           NewYearsMorningHibernation,
    "초월의 열쇠":           ATeaspoonOfTranscendence,
    "늑대의 무용담":          GestOfTheMightyWolf,
    "산왕의 엄니":           FangOfTheMountainKing,
    "갈대 바다의 등대":        BeaconOfTheReedSea,
    "쇄석의 붉은 뿔":         RedhornStonethresher,
    "송뢰가 울릴 무렵":        SongOfBrokenPines,
    "무공의 검":            TheUnforged,
    "늑대의 말로":           WolfsGravestone,
    "천공의 긍지":           SkywardPride,
    "신월의 달빛":           LightbearingMoonshard,
    "검은 침식":            AthameArtis,
    "사면":               Absolution,
    "우라쿠의 미스기리":        UrakuMisugiri,
    "고요히 샘솟는 빛":        SplendorOfTranquilWaters,
    "잎을 가르는 빛":         LightOfFoliarIncision,
    "성현의 열쇠":           KeyOfKhajNisut,
    "하란 월백의 후츠":        HaranGeppakuFutsu,
    "안개를 가르는 회광":       MistsplitterReforged,
    "오래된 자유의 서약":       FreedomSworn,
    "반암결록":             PrimordialJadeCutter,
    "참봉의 칼날":           SummitShaper,
    "적색 사막의 지팡이":       StaffOfTheScarletSands,
    "식재":               CalamityQueller,
    "예초의 번개":           EngulfingLightning,
    "호마의 지팡이":          StaffOfHoma,
    "관홍의 창":            VortexVanquisher,
    "화박연":              PrimordialJadeWingedSpear,
    "서핑 타임":               SurfSUp,
    "현금 흐름 감독":            CashflowSupervision,
    "영원히 샘솟는 법전":          TomeOfTheEternalFlow,
    "벽락의 옥":               JadefallSSplendor,
    "툴레이툴라의 기억":           TulaytullahSRemembrance,
    "떠오르는 천일 밤의 꿈":        AThousandFloatingDreams,
    "카구라의 진의":             KaguraSVerity,
    "불멸의 달빛":              EverlastingMoonglow,
    "속세의 자물쇠":             MemoryOfDust,
    "사풍 원서":               LostPrayerToTheSacredWinds,
    "천공의 두루마리":            SkywardAtlas,
    "밤을 엮는 거울":            NightweaverSLookingGlass,
    "진실의 함":               ReliquaryOfTruth,
    "천공의 날개":              SkywardHarp,
    "아모스의 활":              AmosBow,
}


def make_weapon(
    name:        str,
    refinement:  int,
    weapon_type: WeaponType      | None = None,
    base_atk:    int             | None = None,
    sub_stat:    WeaponSubStat   | None = None,
) -> Weapon:
    cls = WEAPON_REGISTRY.get(name)
    if cls is not None:
        return cls(refinement)
    if weapon_type is None or base_atk is None:
        raise ValueError(
            f"'{name}'은 미등록 무기입니다. weapon_type과 base_atk를 직접 지정하세요."
        )
    return DefaultWeapon(weapon_type, base_atk, refinement, sub_stat)
